server:
  port: 8081
  path: /hello

person:
  lastname: hello
  age: 22
  boss: false
  birth: 2020/11/12
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhangsan
  dog:
    name: 小狗
    age: 2


